### PR TITLE
Rebranded images

### PR DESCRIPTION
**Pull request by nicocartesi**
This is a patch for the MAIN branch. This PR includes rebranded images in the new design colours.

### CODE REVIEW

**Comment by nicocartesi** [comment]
Hi @dimitarangelkov , can you please review this PR? Thanks!

**Comment by nicocartesi** [comment]
Thanks @dimitarangelkov ! Are the updated images ok?

**Comment by dimitarangelkov** [comment]
`Cyan` is the primary colour, so let's use it with priority over `Teal`. The marketing team is trying to reduce the use of the teal colour where possible. So on all images where the only colour is currently `Teal`, let's replace it with `Cyan` to keep it consistent with the overall look. You can use `Teal` when a second or third colour is needed. Also consider black as another background option with white text, it is used a lot in the marketing website.

Screenshot 2023-08-10 at 13 51 45

Here if you can add some padding around `HTTP Rollups Server` text would be great. Looks too close to the surrounding borders. 
dapp-arch

**Comment by nicocartesi** [comment]
Hi @dimitarangelkov , can you please review the updated images?

**Review by karmentruong — APPROVED** [review]

**Review by karmentruong — APPROVED** [review]

**Review by karmentruong — APPROVED** [review]

**Review by gbarros — APPROVED** [review]

**Pull request merged**
