### PR TITLE
180 Update documentation content

### PR DESCRIPTION
**Pull request by nevendyulgerov**
Closes https://github.com/cartesi/docs/issues/180.

### CODE REVIEW

**Comment by brunomenezes** [comment]
@nevendyulgerov, I think you need to include a reviewer here. Maybe @masiedu4 could help with this PR?

**Review by masiedu4 — APPROVED** [review]

**Comment by masiedu4** [comment]
> @nevendyulgerov, I think you need to include a reviewer here. Maybe @masiedu4 could help with this PR?

Approved. You can merge now!

**Comment by nevendyulgerov** [comment]
Hey @masiedu4 , @brunomenezes , I don't have write access to this repo so I cannot add reviewers or merge PRs. If possible, please merge this one on my behalf.

**Comment by brunomenezes** [comment]
> > @nevendyulgerov, I think you need to include a reviewer here. Maybe @masiedu4 could help with this PR?
> 
> Approved. You can merge now!

Nice! Hey @masiedu4, we don't have access to merge the PR. Also, @nevendyulgerov did not even have access rights to add a reviewer. 

Also, one question: **how is the release process once it is merged?** I am asking because once it goes live, I will ping Karmen Truong to have a look.

**Comment by masiedu4** [comment]
> > > @nevendyulgerov, I think you need to include a reviewer here. Maybe @masiedu4 could help with this PR?
> > 
> > 
> > Approved. You can merge now!
> 
> Nice! Hey @masiedu4, we don't have access to merge the PR. Also, @nevendyulgerov did not even have access rights to add a reviewer.
> 
> Also, one question: **how is the release process once it is merged?** I am asking because once it goes live, I will ping Karmen Truong to have a look.

Hi @brunomenezes all the changes are live. Thanks! https://docs.cartesi.io/earn-ctsi/staking/

**Comment by brunomenezes** [comment]
> > > > @nevendyulgerov, I think you need to include a reviewer here. Maybe @masiedu4 could help with this PR?
> > > 
> > > 
> > > Approved. You can merge now!
> > 
> > 
> > Nice! Hey @masiedu4, we don't have access to merge the PR. Also, @nevendyulgerov did not even have access rights to add a reviewer.
> > Also, one question: **how is the release process once it is merged?** I am asking because once it goes live, I will ping Karmen Truong to have a look.
> 
> Hi @brunomenezes all the changes are live. Thanks! https://docs.cartesi.io/earn-ctsi/staking/

Thanks @masiedu4! you're a rockstar 🚀

**Pull request merged**
